### ISSUE TITLE
Collapse Macro

### ISSUE THREAD

**Issue by bmalnersic** [a-ono/redmine_ckeditor#114]
Hi,

having trouble with "collapse macro" (multi-line). 
When wiki page is edited using CKEdit plugin, editing source and inserting code:

{{collapse(View details...)
This is a block of text that is collapsed by default. It can be expanded by clicking a link.
}}

When the page is saved, the macro works.
HTML source:
```
<div class="wiki wiki-page">
  <a class="collapsible collapsed" href="#" id="collapse-f74fa719-show" onclick="$(&#x27;#collapse-f74fa719-show, #collapse-f74fa719-hide&#x27;).toggle(); $(&#x27;#collapse-f74fa719&#x27;).fadeToggle(150);; return false;">View details...</a><a class="collapsible" href="#" id="collapse-f74fa719-hide" onclick="$(&#x27;#collapse-f74fa719-show, #collapse-f74fa719-hide&#x27;).toggle(); $(&#x27;#collapse-f74fa719&#x27;).fadeToggle(150);; return false;" style="display:none;">View details...</a><div class="collapsed-text" id="collapse-f74fa719" style="display:none;">This is a block of text that is collapsed by default. It can be expanded by clicking a link.</div>
```

But when the page is edited and saved for another time, the macro does not work.
HTML source:
```
<p>{{collapse(View details...) This is a block of text that is collapsed by default. It can be expanded by clicking a link. }}</p>
```
Is there a fix for this issue? Or at least a workaround?

Best regards, 

   Blaz

**Comment by a-ono** [comment]
Fixed in master branch.

**Comment by kwslavens** [comment]
I'm experiencing this exact issue on Redmine 3.4 currently. I see that it was supposedly fixed in 2015 but it doesn't appear to be the case. CKeditor is breaking the multi line macro's by forcing them to a single line. I can go to source and same a collapse macro and it works for the until the page is edited and ckeditor turns the line back into a single line which no longer functions. 

Ideas?
