### ISSUE TITLE
Change path for image files

### ISSUE THREAD

**Issue by hriekehof** [a-ono/redmine_ckeditor#174]
Hi,

i installed ckeditor 1.0.20 in redmine 2.6 and it runs fine. Besides i had trouble with the image uploads using rich. Somehow the editor wants to save the files in redmine/public/system which is non existent in a normal redmine installation as far as i know.
If i create that folder with the correct rights everything seems to work. 

From the configuration point of view i think its better when the files from the rich plugin are also stored in the /files folder as the other files from redmine are stored too.

I wasn't able to finde the place where i can configure the folder which rich uses to store the uploaded images ?
Can anyone help ?

**Comment by ericLemanissier** [comment]
@a-ono This issue is absolutely critical. the current path used to store images (~/redmine/public/system/rich/rich_files/rich_files/) is not referenced anywhere, and is not backed up. The consequence is that all these files are lost when doing a redmine upgrade when docker is used (eg https://github.com/sameersbn/docker-redmine). the default storage should be inside ~/redmine/data, or at least it should be configurable

**Comment by hriekehof** [comment]
i close this now to get rid of it in my issue list :) sorry
