### ISSUE TITLE
Option to disable on a userbasis

### ISSUE THREAD

**Issue by stffndtz** [a-ono/redmine_ckeditor#187]
I'd like to see an option, that let's users enable or disable the ckeditor.

Has anyone had any thoughts about this so far?

Thanks in advance!

**Comment by rompic** [comment]
correct me if i'm wrong, but i think that's not really possible, because ckeditor creates html and stores it in the DB while otherwise e.g. textile would be used.

**Comment by DarkSideGeek** [comment]
Redmine's editor hook does not translate from one format to another. It merely takes the output and saves it to the DB. To make it user-pref would require translation from Textile to HTML and vice versa. We use the per-project plugin and just make the editor choice a responsibility of the project owner that all members must live with. You can change format, but then you have to reformat all the text...

**Comment by stffndtz** [comment]
@rompic Thanks, I understand that that is an issue.

@DarkSideGeek Does the plugin (I suppose it's that one? https://github.com/a-ono/redmine_per_project_formatting) support the option out of the box?

Thanks a lot for your answers!

**Comment by DarkSideGeek** [comment]
Yes, that is the per-project plugin I was speaking of. It allows project owners to establish an Editor standard within the confines of each particular project. You can even restrict it to certain modules within the project (eg Wiki but not Issues). In the project Settings page, you have a choice of textile, markdown, CKeditor (if installed), and "whatever the Admin set as the global default". All members then live with that choice. 

It works really well, but it is not per-user. Also, it does no translating between formats, so if you built a project as HTML (CK) and then decided to switch, you would have to manually reformat those docs.

I think having the editor do the translating would be difficult because it would have to handle a (theoretically) infinite number of formats. I found an old Redmine thread where they talked about storing text as XHTML such that editors would have a universal base to start from. That would have helped here, but I don't think they ever implemented it.

**Comment by stffndtz** [comment]
It worked like a charm, and it fits our needs just as well as the per-user option.

Thanks again, I'll close this ticket since I feel there's arguably too many obstacles to overcome!
