### ISSUE TITLE
Line breaks of incoming mails lost

### ISSUE THREAD

**Issue by hastep** [a-ono/redmine_ckeditor#89]
This plugin looks very promising since we're looking for a WYSIWYG editor for the Redmine wiki pages.  We've come across one problem during testing, though, and I'm wondering if others have run into this and might have a solution.

We use the receive_imap rake task to allow issues to be opened and updated via e-mail (see http://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails#Fetching-emails-from-an-IMAP-server).  Without the CKEditor, the formatting of incoming mails is lost, but line breaks are still interpreted correctly, making mails readable.  If CKEditor is  used, however, all line breaks are lost and the description appears as one giant, continuous paragraph.

Does anyone know if there's a solution or workaround to this?

BTW, this also happens if an e-mail is received and interpreted correctly in a project set to textile formatting and the issue then moved to a project configured to use CKEditor.

**Comment by JT1301** [comment]
Hi, I'm sorry to reopen an already closed ticket but it doesn't work for me.

No line breaks are inserted in the text. 
Is there another way to add the line breaks since 2014?

**Comment by imendiola** [comment]
I am having the same issue newer versions of Redmine and CKEditor plugin:
- Redmine 4.1.1.stable
- CKEditor plugin 1.2.3

UPDATE: it seems that it was caused by other plugin... in this case, it was  redmine_contacts_helpdesk-4_1_7. Updating to redmine_contacts_helpdesk-4_1_8 solved the issue.
I apologize for the inconvenience
